# Change these first
owner: Salty-Coder # Your GitHub organization or username, where this repository lives
repo: salty-site-status # The name of this repository

sites:
  - name: Salty Website
    url: https://saltyspamz.xyz
  - name: Salty Suite Website
    url: https://suite.saltyspamz.xyz
  - name: Salty Suite Account System
    url: $SSUITE_URL
    expectedStatusCodes:
      - 404
  - name: Minecraft Classic Multiplayer Server
    url: $MCCLAS_URL
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.saltyspamz.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://saltyspamz.xyz/logo.png
  name: Salty Status
  introTitle: "Salty Spamz Service Status"
  introMessage: Check here for any outages in our servers.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://saltyspamz.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
